### ISSUE TITLE
.Net 5.0 (Out of Support)

### ISSUE THREAD

**Issue by solidcloudio** [microsoft/service-fabric-yarp#13]
This solution is using .NET 5.0 (Out of support) - Can we get it upgraded to a supported version ?

**Comment by solidcloudio** [comment]
submitted a PR to upgrade to .net 6.0

**Comment by vince-antonio-insurity** [comment]
Is there a version of service-fabric-yarp that supports NET 6.0?  I see this issue was closed after a PR was submitted, however the projects are still targeting NET 5.0 in the latest release.
