### ISSUE TITLE
Clarification: Host-based matching

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/service-fabric-yarp#4]
The README in the root reads that "Path-based route matching is ONLY supported.". 

Will this also support host-based matching like the original SF YARP implementation?

Thanks!

**Comment by egaribay77** [comment]
Hello, yes, we will be adding host-based route matching and try to extend the label support to add more YARP config options.

**Comment by egaribay77** [comment]
This is now supported with the latest release. Take a look at the recent PR: https://github.com/microsoft/service-fabric-yarp/pull/10
