### ISSUE TITLE
Unable to Register Pinger Test Application

### ISSUE THREAD

**Issue by fuhsb** [microsoft/service-fabric-yarp#6]
I downloaded the service-fabric-yarp.zip and followed the instructions in deploying YARP using PowerShell. That looks to have deployed correctly. We wanted to test out the YARP deployment by using the pinger test application provided. When I get to the step **Register-ServiceFabricApplicationType -ApplicationPathInImageStore pinger-yarp**, I get the below error:

```
Register-ServiceFabricApplicationType : The BuildLayout of the application in S:\SvcFab\ImageBuilderProxy\AppType\d2dbaf41-1f22-4fab-b012-5a52b7e29487 is invalid. Pinger.Code is missing for service PingerService.
At line:1 char:1
+ Register-ServiceFabricApplicationType -ApplicationPathInImageStore pi ...
+ CategoryInfo: InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Register-ServiceFabricApplicationType], FabricException
+ FullyQualifiedErrorId : RegisterApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.RegisterApplicationType
```

Is there a step I'm missing prior to or after downloading the SF yarp zip file? Every step I've taken is verbatim with what you have provided.

**Comment by egaribay77** [comment]
Hello, I just took a look, and it seems as the pinger.exe was not added to the pinger.code package for the latest release. It must have not been properly added as part of our pipeline release. For now, can you download the previous release zip and extract the pinger.exe and add it manually

**Comment by egaribay77** [comment]
This has been addressed by the recent PR: https://github.com/microsoft/service-fabric-yarp/pull/10
