### ISSUE TITLE
.NET 5 to .NET 6 Upgrade

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/service-fabric-yarp#7]
As .NET 5 is about to lose support, is there work being done to upgrade this to use .NET 6 throughout? Or would you accept a PR that does the same?

**Comment by Tratcher** [comment]
Are you having any trouble running the project on .NET 6? Target Frameworks do not go out of support, only runtimes.

**Comment by WhitWaldo** [comment]
Sorry, I was out of town over the weekend and for the life of me, could not get this to work on my laptop as it kept insisting that I needed to have .NET Framework 4 installed.

I was planning on giving it another shot on my development system and see if I have any better luck.

**Comment by WhitWaldo** [comment]
So just did a fresh clone on my development desktop and while I don't see any of the .NET Framework 4 errors, I'm also unable to build as-is from either the latest git comment or the zipped source release with the error "MSB4057 The target 'CreateManifestResourceNames' does not exist in the project".

**Comment by egaribay77** [comment]
Hello, after you clone the repo can you try to restoring it using the following command "msbuild /t:build /restore". If you are still facing the issue can you add the entire error msg.

**Comment by solidcloudio** [comment]
I submitted a PR to upgrade to .net 6.0
